<?php
$AUTH_METHOD = "none";
$AUTH_SOURCE = "1";
$AUTH_USER = "";
$CASCADING = "0";
$CAS_SERVER = "";
$CAS_PORT = "";
$CAS_AUTH_USER = "";
$CAS_AUTH_PASS = "";
$CAS_AUTH_PASSTHROUGH = "1";
$LOGLEVEL = "2";
$LOGFILE = "satellite_proxy.log";
$MAXLOGSIZE = "4000000";
$TKEEPALIVE_ENABLE = "1";
$TKEEPALIVE_INTERVAL = "10";
$IPC_LOADBALANCE = "";
$IPC_TMPDIR = "/tmp/";
$ID_ENABLE = "";
$ID_TIMEOUT = "30";
$ID_BANTIMEOUT = "600";
$ID_MAXACCESS = "3";
$ENCRYPTION_FORCE = "";
$SEC_IP = "";
?>
